import product2a from '../assets/images/product-2-1.jpg';
import product2b from '../assets/images/product-2-2.jpg';
export const demoProducts = [
    {
        id: 0,
        img: [product2a, product2b],
        price: 206,
        discount: 0,
        category: 'jean',
    },
    {
        id: 1,
        img: [product2a, product2b],
        price: 204,
        discount: 0,
        category: 'jean',
    },
    {
        id: 2,
        img: [product2a, product2b],
        price: 233,
        discount: 10,
        category: 'jean',
    },
    {
        id: 3,
        img: [product2a, product2b],
        price: 172,
        discount: 0,
        category: 'jean',
    },
    {
        id: 4,
        img: [product2a, product2b],
        price: 182,
        discount: 15,
        category: 'jean',
    },
    {
        id: 5,
        img: [product2a, product2b],
        price: 226,
        discount: 0,
        category: 'jean',
    },
    {
        id: 6,
        img: [product2a, product2b],
        price: 170,
        discount: 0,
        category: 'jean',
    },
    {
        id: 7,
        img: [product2a, product2b],
        price: 204,
        discount: 0,
        category: 'jean',
    },
    {
        id: 8,
        img: [product2a, product2b],
        price: 198,
        discount: 0,
        category: 'jean',
    },
    {
        id: 9,
        img: [product2a, product2b],
        price: 200,
        discount: 0,
        category: 'jean',
    },
    {
        id: 10,
        img: [product2a, product2b],
        price: 200,
        discount: 0,
        category: 'jean',
    },
    {
        id: 11,
        img: [product2a, product2b],
        price: 211,
        discount: 0,
        category: 'tshirt',
    },
    {
        id: 12,
        img: [product2a, product2b],
        price: 211,
        discount: 45,
        category: 'tshirt',
    },
    {
        id: 13,
        img: [product2a, product2b],
        price: 238,
        discount: 45,
        category: 'tshirt',
    },
    {
        id: 14,
        img: [product2a, product2b],
        price: 182,
        discount: 45,
        category: 'tshirt',
    },
    {
        id: 15,
        img: [product2a, product2b],
        price: 220,
        discount: 45,
        category: 'tshirt',
    },
    {
        id: 16,
        img: [product2a, product2b],
        price: 237,
        discount: 45,
        category: 'tshirt',
    },
    {
        id: 17,
        img: [product2a, product2b],
        price: 233,
        discount: 45,
        category: 'jean',
    },
    {
        id: 18,
        img: [product2a, product2b],
        price: 226,
        discount: 45,
        category: 'jean',
    },
    {
        id: 19,
        img: [product2a, product2b],
        price: 221,
        discount: 45,
        category: 'jean',
    },
    {
        id: 20,
        img: [product2a, product2b],
        price: 217,
        discount: 45,
        category: 'dresses',
    },
    {
        id: 21,
        img: [product2a, product2b],
        price: 212,
        discount: 45,
        category: 'dresses',
    },
    {
        id: 22,
        img: [product2a, product2b],
        price: 214,
        discount: 45,
        category: 'dresses',
    },
    {
        id: 23,
        img: [product2a, product2b],
        price: 220,
        discount: 45,
        category: 'dresses',
    },
    {
        id: 24,
        img: [product2a, product2b],
        price: 208,
        discount: 45,
        category: 'dresses',
    },
    {
        id: 25,
        img: [product2a, product2b],
        price: 191,
        discount: 0,
        category: 'dresses',
    },
    {
        id: 26,
        img: [product2a, product2b],
        price: 205,
        discount: 0,
        category: 'dresses',
    },
    {
        id: 27,
        img: [product2a, product2b],
        price: 198,
        discount: 0,
        category: 'dresses',
    },
    {
        id: 28,
        img: [product2a, product2b],
        price: 206,
        discount: 0,
        category: 'dresses',
    },
    {
        id: 29,
        img: [product2a, product2b],
        price: 176,
        discount: 0,
        category: 'dresses',
    },
    {
        id: 30,
        img: [product2a, product2b],
        price: 169,
        discount: 0,
        category: 'dresses',
    },
    {
        id: 31,
        img: [product2a, product2b],
        price: 200,
        discount: 0,
        category: 'dresses',
    },
    {
        id: 32,
        img: [product2a, product2b],
        price: 173,
        discount: 0,
        category: 'jean',
    },
    {
        id: 33,
        img: [product2a, product2b],
        price: 190,
        discount: 30,
        category: 'jean',
    },
    {
        id: 34,
        img: [product2a, product2b],
        price: 206,
        discount: 30,
        category: 'jean',
    },
    {
        id: 35,
        img: [product2a, product2b],
        price: 195,
        discount: 30,
        category: 'jean',
    },
    {
        id: 36,
        img: [product2a, product2b],
        price: 211,
        discount: 30,
        category: 'jacket',
    },
    {
        id: 37,
        img: [product2a, product2b],
        price: 228,
        discount: 30,
        category: 'jacket',
    },
    {
        id: 38,
        img: [product2a, product2b],
        price: 231,
        discount: 30,
        category: 'jacket',
    },
    {
        id: 39,
        img: [product2a, product2b],
        price: 227,
        discount: 30,
        category: 'jacket',
    },
    {
        id: 40,
        img: [product2a, product2b],
        price: 221,
        discount: 30,
        category: 'jacket',
    },
    {
        id: 41,
        img: [product2a, product2b],
        price: 179,
        discount: 30,
        category: 'jacket',
    },
    {
        id: 42,
        img: [product2a, product2b],
        price: 192,
        discount: 30,
        category: 'jacket',
    },
    {
        id: 43,
        img: [product2a, product2b],
        price: 193,
        discount: 30,
        category: 'jacket',
    },
    {
        id: 44,
        img: [product2a, product2b],
        price: 218,
        discount: 30,
        category: 'jacket',
    },
    {
        id: 45,
        img: [product2a, product2b],
        price: 212,
        discount: 30,
        category: 'jacket',
    },
    {
        id: 46,
        img: [product2a, product2b],
        price: 211,
        discount: 30,
        category: 'jacket',
    },
    {
        id: 47,
        img: [product2a, product2b],
        price: 205,
        discount: 30,
        category: 'jacket',
    },
    {
        id: 48,
        img: [product2a, product2b],
        price: 197,
        discount: 30,
        category: 'jacket',
    },
    {
        id: 49,
        img: [product2a, product2b],
        price: 188,
        discount: 30,
        category: 'jacket',
    },
    {
        id: 50,
        img: [product2a, product2b],
        price: 228,
        discount: 0,
        category: 'jacket',
    },
    {
        id: 51,
        img: [product2a, product2b],
        price: 194,
        discount: 0,
        category: 'jacket',
    },
    {
        id: 52,
        img: [product2a, product2b],
        price: 241,
        discount: 0,
        category: 'jacket',
    },
    {
        id: 53,
        img: [product2a, product2b],
        price: 190,
        discount: 0,
        category: 'jacket',
    },
    {
        id: 54,
        img: [product2a, product2b],
        price: 194,
        discount: 0,
        category: 'jacket',
    },
    {
        id: 55,
        img: [product2a, product2b],
        price: 177,
        discount: 0,
        category: 'jacket',
    },
    {
        id: 56,
        img: [product2a, product2b],
        price: 237,
        discount: 0,
        category: 'jacket',
    },
    {
        id: 57,
        img: [product2a, product2b],
        price: 172,
        discount: 0,
        category: 'jacket',
    },
    {
        id: 58,
        img: [product2a, product2b],
        price: 247,
        discount: 0,
        category: 'jacket',
    },
    {
        id: 59,
        img: [product2a, product2b],
        price: 192,
        discount: 0,
        category: 'jacket',
    },
    {
        id: 60,
        img: [product2a, product2b],
        price: 170,
        discount: 0,
        category: 'jacket',
    },
    {
        id: 61,
        img: [product2a, product2b],
        price: 224,
        discount: 0,
        category: 'jacket',
    },
    {
        id: 62,
        img: [product2a, product2b],
        price: 224,
        discount: 20,
        category: 'jean',
    },
    {
        id: 63,
        img: [product2a, product2b],
        price: 229,
        discount: 20,
        category: 'san.d',
    },
    {
        id: 64,
        img: [product2a, product2b],
        price: 244,
        discount: 20,
        category: 'san.d',
    },
    {
        id: 65,
        img: [product2a, product2b],
        price: 185,
        discount: 20,
        category: 'san.d',
    },
    {
        id: 66,
        img: [product2a, product2b],
        price: 213,
        discount: 20,
        category: 'san.d',
    },
    {
        id: 67,
        img: [product2a, product2b],
        price: 179,
        discount: 20,
        category: 'san.d',
    },
    {
        id: 68,
        img: [product2a, product2b],
        price: 231,
        discount: 20,
        category: 'san.d',
    },
    {
        id: 69,
        img: [product2a, product2b],
        price: 212,
        discount: 20,
        category: 'jean',
    },
    {
        id: 70,
        img: [product2a, product2b],
        price: 242,
        discount: 20,
        category: 'jean',
    },
    {
        id: 71,
        img: [product2a, product2b],
        price: 222,
        discount: 20,
        category: 'jean',
    },
    {
        id: 72,
        img: [product2a, product2b],
        price: 247,
        discount: 20,
        category: 'jean',
    },
    {
        id: 73,
        img: [product2a, product2b],
        price: 245,
        discount: 0,
        category: 'jean',
    },
    {
        id: 74,
        img: [product2a, product2b],
        price: 219,
        discount: 0,
        category: 'jean',
    },
    {
        id: 75,
        img: [product2a, product2b],
        price: 220,
        discount: 0,
        category: 'jean',
    },
    {
        id: 76,
        img: [product2a, product2b],
        price: 209,
        discount: 0,
        category: 'jean',
    },
    {
        id: 77,
        img: [product2a, product2b],
        price: 235,
        discount: 0,
        category: 'jean',
    },
    {
        id: 78,
        img: [product2a, product2b],
        price: 239,
        discount: 0,
        category: 'jean',
    },
    {
        id: 79,
        img: [product2a, product2b],
        price: 246,
        discount: 0,
        category: 'jean',
    },
    {
        id: 80,
        img: [product2a, product2b],
        price: 191,
        discount: 0,
        category: 'featured',
    },
    {
        id: 81,
        img: [product2a, product2b],
        price: 211,
        discount: 0,
        category: 'featured',
    },
    {
        id: 82,
        img: [product2a, product2b],
        price: 205,
        discount: 0,
        category: 'featured',
    },
    {
        id: 83,
        img: [product2a, product2b],
        price: 198,
        discount: 0,
        category: 'featured',
    },
    {
        id: 84,
        img: [product2a, product2b],
        price: 171,
        discount: 17,
        category: 'featured',
    },
    {
        id: 85,
        img: [product2a, product2b],
        price: 248,
        discount: 17,
        category: 'featured',
    },
    {
        id: 86,
        img: [product2a, product2b],
        price: 205,
        discount: 17,
        category: 'featured',
    },
    {
        id: 87,
        img: [product2a, product2b],
        price: 177,
        discount: 17,
        category: 'jean',
    },
    {
        id: 88,
        img: [product2a, product2b],
        price: 187,
        discount: 17,
        category: 'jean',
    },
    {
        id: 89,
        img: [product2a, product2b],
        price: 195,
        discount: 17,
        category: 'jean',
    },
    {
        id: 90,
        img: [product2a, product2b],
        price: 225,
        discount: 17,
        category: 'jean',
    },
    {
        id: 91,
        img: [product2a, product2b],
        price: 246,
        discount: 17,
        category: 'jean',
    },
    {
        id: 92,
        img: [product2a, product2b],
        price: 179,
        discount: 17,
        category: 'jean',
    },
    {
        id: 93,
        img: [product2a, product2b],
        price: 184,
        discount: 17,
        category: 'jean',
    },
    {
        id: 94,
        img: [product2a, product2b],
        price: 179,
        discount: 17,
        category: 'jean',
    },
    {
        id: 95,
        img: [product2a, product2b],
        price: 169,
        discount: 17,
        category: 'jean',
    },
    {
        id: 96,
        img: [product2a, product2b],
        price: 216,
        discount: 17,
        category: 'jean',
    },
    {
        id: 97,
        img: [product2a, product2b],
        price: 227,
        discount: 0,
        category: 'san.d',
    },
    {
        id: 98,
        img: [product2a, product2b],
        price: 171,
        discount: 0,
        category: 'san.d',
    },
    {
        id: 99,
        img: [product2a, product2b],
        price: 207,
        discount: 0,
        category: 'san.d',
    },
    {
        id: 100,
        img: [product2a, product2b],
        price: 231,
        discount: 0,
        category: 'san.d',
    },
];

export const productsPerPage = 12; 
