import product2a from '../assets/images/product-2-1.jpg';
import product2b from '../assets/images/product-2-2.jpg';
export const demoProducts = [
    {
        id: 0,
        img: [product2a, product2b, product2a, product2b],
        price: 206,
        discount: 0,
        category: 'jean',
        title: 'Skinny Jeans',
    },
    {
        id: 1,
        img: [product2a, product2b, product2a, product2b],
        price: 204,
        discount: 0,
        category: 'jean',
        title: 'Straight Leg Jeans',
    },
    {
        id: 2,
        img: [product2a, product2b, product2a, product2b],
        price: 233,
        discount: 10,
        category: 'jean',
        title: 'Flare Jeans',
    },
    {
        id: 3,
        img: [product2a, product2b, product2a, product2b],
        price: 172,
        discount: 0,
        category: 'jean',
        title: 'Wide Leg Jeans',
    },
    {
        id: 4,
        img: [product2a, product2b, product2a, product2b],
        price: 182,
        discount: 15,
        category: 'jean',
        title: 'Bootcut Jeans',
    },
    {
        id: 15,
        img: [product2a, product2b, product2a, product2b],
        price: 220,
        discount: 45,
        category: 'tshirt',
        title: 'Long-Sleeve T-Shirt',
    },
    {
        id: 5,
        img: [product2a, product2b, product2a, product2b],
        price: 226,
        discount: 0,
        category: 'jean',
        title: 'Boyfriend Jeans',
    },
    {
        id: 6,
        img: [product2a, product2b, product2a, product2b],
        price: 170,
        discount: 0,
        category: 'jean',
        title: 'Mom Jeans',
    },
    {
        id: 7,
        img: [product2a, product2b, product2a, product2b],
        price: 204,
        discount: 0,
        category: 'jean',
        title: 'High-Waisted Jeans',
    },
    {
        id: 8,
        img: [product2a, product2b, product2a, product2b],
        price: 198,
        discount: 0,
        category: 'jean',
        title: 'Low-Rise Jeans',
    },
    {
        id: 9,
        img: [product2a, product2b, product2a, product2b],
        price: 200,
        discount: 0,
        category: 'tshirt',
        title: 'Classic T-Shirt',
    },
    {
        id: 10,
        img: [product2a, product2b, product2a, product2b],
        price: 200,
        discount: 0,
        category: 'tshirt',
        title: 'Graphic T-Shirt',
    },
    {
        id: 11,
        img: [product2a, product2b, product2a, product2b],
        price: 211,
        discount: 0,
        category: 'tshirt',
        title: 'V-Neck T-Shirt',
    },
    {
        id: 12,
        img: [product2a, product2b, product2a, product2b],
        price: 211,
        discount: 45,
        category: 'tshirt',
        title: 'Crew Neck T-Shirt',
    },
    {
        id: 13,
        img: [product2a, product2b, product2a, product2b],
        price: 238,
        discount: 45,
        category: 'tshirt',
        title: 'Striped T-Shirt',
    },
    {
        id: 14,
        img: [product2a, product2b, product2a, product2b],
        price: 182,
        discount: 45,
        category: 'tshirt',
        title: 'Solid Color T-Shirt',
    },

    {
        id: 16,
        img: [product2a, product2b, product2a, product2b],
        price: 237,
        discount: 45,
        category: 'tshirt',
        title: 'Henley T-Shirt',
    },
    {
        id: 17,
        img: [product2a, product2b, product2a, product2b],
        price: 233,
        discount: 45,
        category: 'tshirt',
        title: 'Polo Shirt',
    },
    {
        id: 18,
        img: [product2a, product2b, product2a, product2b],
        price: 226,
        discount: 45,
        category: 'tshirt',
        title: 'Sleeveless T-Shirt',
    },
    {
        id: 19,
        img: [product2a, product2b, product2a, product2b],
        price: 221,
        discount: 45,
        category: 'jean',
        title: 'Crop Jeans',
    },
    {
        id: 20,
        img: [product2a, product2b, product2a, product2b],
        price: 217,
        discount: 45,
        category: 'dresses',
        title: 'Off-Shoulder Dress',
    },
    {
        id: 21,
        img: [product2a, product2b, product2a, product2b],
        price: 212,
        discount: 45,
        category: 'dresses',
        title: 'Maxi Dress',
    },
    {
        id: 22,
        img: [product2a, product2b, product2a, product2b],
        price: 214,
        discount: 45,
        category: 'dresses',
        title: 'A-Line Dress',
    },
    {
        id: 23,
        img: [product2a, product2b, product2a, product2b],
        price: 220,
        discount: 45,
        category: 'dresses',
        title: 'Sheath Dress',
    },
    {
        id: 24,
        img: [product2a, product2b, product2a, product2b],
        price: 208,
        discount: 45,
        category: 'dresses',
        title: 'Shirt Dress',
    },
    {
        id: 25,
        img: [product2a, product2b, product2a, product2b],
        price: 191,
        discount: 0,
        category: 'dresses',
        title: 'Wrap Dress',
    },
    {
        id: 26,
        img: [product2a, product2b, product2a, product2b],
        price: 205,
        discount: 0,
        category: 'dresses',
        title: 'Sundress',
    },
    {
        id: 27,
        img: [product2a, product2b, product2a, product2b],
        price: 198,
        discount: 0,
        category: 'dresses',
        title: 'Shift Dress',
    },
    {
        id: 28,
        img: [product2a, product2b, product2a, product2b],
        price: 206,
        discount: 0,
        category: 'dresses',
        title: 'Bodycon Dress',
    },
    {
        id: 29,
        img: [product2a, product2b, product2a, product2b],
        price: 176,
        discount: 0,
        category: 'dresses',
        title: 'Skater Dress',
    },
    {
        id: 30,
        img: [product2a, product2b, product2a, product2b],
        price: 169,
        discount: 0,
        category: 'dresses',
        title: 'Thailand Dress',
    },
    {
        id: 31,
        img: [product2a, product2b, product2a, product2b],
        price: 200,
        discount: 0,
        category: 'dresses',
        title: 'BA Dress',
    },
    {
        id: 32,
        img: [product2a, product2b, product2a, product2b],
        price: 173,
        discount: 0,
        category: 'jean',
        title: 'Distressed Jeans',
    },
    {
        id: 33,
        img: [product2a, product2b, product2a, product2b],
        price: 190,
        discount: 30,
        category: 'jean',
        title: 'Ripped Jeans',
    },
    {
        id: 34,
        img: [product2a, product2b, product2a, product2b],
        price: 206,
        discount: 30,
        category: 'jean',
        title: 'Raw Hem Jeans',
    },
    {
        id: 35,
        img: [product2a, product2b, product2a, product2b],
        price: 195,
        discount: 30,
        category: 'jean',
        title: 'Embroidered Jeans',
    },
    {
        id: 36,
        img: [product2a, product2b, product2a, product2b],
        price: 211,
        discount: 30,
        category: 'jacket',
        title: 'Trend Jacket',
    },
    {
        id: 37,
        img: [product2a, product2b, product2a, product2b],
        price: 228,
        discount: 30,
        category: 'jacket',
        title: 'Trent Jacket',
    },
    {
        id: 38,
        img: [product2a, product2b, product2a, product2b],
        price: 231,
        discount: 30,
        category: 'jacket',
        title: 'Trench Jacket',
    },
    {
        id: 39,
        img: [product2a, product2b, product2a, product2b],
        price: 227,
        discount: 30,
        category: 'jacket',
        title: 'Parka Jacket 2',
    },
    {
        id: 40,
        img: [product2a, product2b, product2a, product2b],
        price: 221,
        discount: 30,
        category: 'jacket',
        title: 'Hooded Jacket',
    },
    {
        id: 41,
        img: [product2a, product2b, product2a, product2b],
        price: 179,
        discount: 30,
        category: 'jacket',
        title: 'Puffer Jacket',
    },
    {
        id: 42,
        img: [product2a, product2b, product2a, product2b],
        price: 192,
        discount: 30,
        category: 'jacket',
        title: 'Parka Jacket',
    },
    {
        id: 43,
        img: [product2a, product2b, product2a, product2b],
        price: 193,
        discount: 30,
        category: 'jacket',
        title: 'Blazer Jacket',
    },
    {
        id: 44,
        img: [product2a, product2b, product2a, product2b],
        price: 218,
        discount: 30,
        category: 'jacket',
        title: 'Peacoat Jacket',
    },
    {
        id: 45,
        img: [product2a, product2b, product2a, product2b],
        price: 212,
        discount: 30,
        category: 'jacket',
        title: 'Trench Coat',
    },
    {
        id: 46,
        img: [product2a, product2b, product2a, product2b],
        price: 211,
        discount: 30,
        category: 'jacket',
        title: 'Biker Jacket',
    },
    {
        id: 47,
        img: [product2a, product2b, product2a, product2b],
        price: 205,
        discount: 30,
        category: 'jacket',
        title: 'Faux Fur Jacket',
    },
    {
        id: 48,
        img: [product2a, product2b, product2a, product2b],
        price: 197,
        discount: 30,
        category: 'jacket',
        title: 'Field Jacket',
    },
    {
        id: 49,
        img: [product2a, product2b, product2a, product2b],
        price: 188,
        discount: 30,
        category: 'jacket',
        title: 'Fleece Jacket',
    },
    {
        id: 50,
        img: [product2a, product2b, product2a, product2b],
        price: 228,
        discount: 0,
        category: 'jacket',
        title: 'Trucker Jacket',
    },
    {
        id: 51,
        img: [product2a, product2b, product2a, product2b],
        price: 194,
        discount: 0,
        category: 'jacket',
        title: 'Rain Jacket',
    },
    {
        id: 52,
        img: [product2a, product2b, product2a, product2b],
        price: 241,
        discount: 0,
        category: 'jacket',
        title: 'Quilted Jacket',
    },
    {
        id: 53,
        img: [product2a, product2b, product2a, product2b],
        price: 190,
        discount: 0,
        category: 'jacket',
        title: 'Varsity Jacket',
    },
    {
        id: 54,
        img: [product2a, product2b, product2a, product2b],
        price: 194,
        discount: 0,
        category: 'jacket',
        title: 'Snow Jacket',
    },
    {
        id: 55,
        img: [product2a, product2b, product2a, product2b],
        price: 177,
        discount: 0,
        category: 'jacket',
        title: 'Moto Jacket',
    },
    {
        id: 56,
        img: [product2a, product2b, product2a, product2b],
        price: 237,
        discount: 0,
        category: 'jacket',
        title: 'ABC Jacket',
    },
    {
        id: 57,
        img: [product2a, product2b, product2a, product2b],
        price: 172,
        discount: 0,
        category: 'jacket',
        title: 'ABC Jacket',
    },
    {
        id: 58,
        img: [product2a, product2b, product2a, product2b],
        price: 247,
        discount: 0,
        category: 'jacket',
        title: 'Bomber Jacket',
    },
    {
        id: 59,
        img: [product2a, product2b, product2a, product2b],
        price: 192,
        discount: 0,
        category: 'jacket',
        title: 'Leather Jacket',
    },
    {
        id: 60,
        img: [product2a, product2b, product2a, product2b],
        price: 170,
        discount: 0,
        category: 'jacket',
        title: 'Denim Jacket',
    },
    {
        id: 61,
        img: [product2a, product2b, product2a, product2b],
        price: 224,
        discount: 0,
        category: 'jacket',
        title: 'Windbreaker Jacket',
    },
    {
        id: 62,
        img: [product2a, product2b, product2a, product2b],
        price: 224,
        discount: 20,
        category: 'jean',
        title: 'Embellished Jeans',
    },
    {
        id: 63,
        img: [product2a, product2b, product2a, product2b],
        price: 229,
        discount: 20,
        category: 'san.d',
        title: 'Classic Polo San.D',
    },
    {
        id: 64,
        img: [product2a, product2b, product2a, product2b],
        price: 244,
        discount: 20,
        category: 'san.d',
        title: 'Slim Fit Polo San.D',
    },
    {
        id: 65,
        img: [product2a, product2b, product2a, product2b],
        price: 185,
        discount: 20,
        category: 'san.d',
        title: 'Striped Polo San.D',
    },
    {
        id: 66,
        img: [product2a, product2b, product2a, product2b],
        price: 213,
        discount: 20,
        category: 'san.d',
        title: 'Cotton Polo San.D',
    },
    {
        id: 67,
        img: [product2a, product2b, product2a, product2b],
        price: 179,
        discount: 20,
        category: 'san.d',
        title: 'Sporty Polo San.D',
    },
    {
        id: 68,
        img: [product2a, product2b, product2a, product2b],
        price: 231,
        discount: 20,
        category: 'san.d',
        title: 'Performance Polo San.D',
    },
    {
        id: 69,
        img: [product2a, product2b, product2a, product2b],
        price: 212,
        discount: 20,
        category: 'jean',
        title: 'Cropped Flare Jeans',
    },
    {
        id: 70,
        img: [product2a, product2b, product2a, product2b],
        price: 242,
        discount: 20,
        category: 'jean',
        title: 'Cuffed Jeans',
    },
    {
        id: 71,
        img: [product2a, product2b, product2a, product2b],
        price: 222,
        discount: 20,
        category: 'jean',
        title: 'Paperbag Waist Jeans',
    },
    {
        id: 72,
        img: [product2a, product2b, product2a, product2b],
        price: 247,
        discount: 20,
        category: 'jean',
        title: 'Cargo Jeans',
    },
    {
        id: 73,
        img: [product2a, product2b, product2a, product2b],
        price: 245,
        discount: 0,
        category: 'jean',
        title: 'Overalls',
    },
    {
        id: 74,
        img: [product2a, product2b, product2a, product2b],
        price: 219,
        discount: 0,
        category: 'jean',
        title: 'Jeggings',
    },
    {
        id: 75,
        img: [product2a, product2b, product2a, product2b],
        price: 220,
        discount: 0,
        category: 'jean',
        title: 'Stretch Jeans',
    },
    {
        id: 76,
        img: [product2a, product2b, product2a, product2b],
        price: 209,
        discount: 0,
        category: 'jean',
        title: 'Acid Wash Jeans',
    },
    {
        id: 77,
        img: [product2a, product2b, product2a, product2b],
        price: 235,
        discount: 0,
        category: 'jean',
        title: 'Vintage Jeans',
    },
    {
        id: 78,
        img: [product2a, product2b, product2a, product2b],
        price: 239,
        discount: 0,
        category: 'jean',
        title: 'Frayed Hem Jeans',
    },
    {
        id: 79,
        img: [product2a, product2b, product2a, product2b],
        price: 246,
        discount: 0,
        category: 'jean',
        title: 'White Jeans',
    },
    {
        id: 80,
        img: [product2a, product2b, product2a, product2b],
        price: 191,
        discount: 0,
        category: 'featured',
        title: 'Dress San.D',
    },
    {
        id: 81,
        img: [product2a, product2b, product2a, product2b],
        price: 211,
        discount: 0,
        category: 'featured',
        title: 'Polo San.D',
    },
    {
        id: 82,
        img: [product2a, product2b, product2a, product2b],
        price: 205,
        discount: 0,
        category: 'featured',
        title: 'T-shirt San.D',
    },
    {
        id: 83,
        img: [product2a, product2b, product2a, product2b],
        price: 198,
        discount: 0,
        category: 'featured',
        title: 'Clothes San.D',
    },
    {
        id: 84,
        img: [product2a, product2b, product2a, product2b],
        price: 171,
        discount: 17,
        category: 'featured',
        title: 'Bag San.D',
    },
    {
        id: 85,
        img: [product2a, product2b, product2a, product2b],
        price: 248,
        discount: 17,
        category: 'featured',
        title: 'Shoes San.D',
    },
    {
        id: 86,
        img: [product2a, product2b, product2a, product2b],
        price: 205,
        discount: 17,
        category: 'featured',
        title: 'Clothes San.D',
    },
    {
        id: 87,
        img: [product2a, product2b, product2a, product2b],
        price: 177,
        discount: 17,
        category: 'jean',
        title: 'Black Jeans',
    },
    {
        id: 88,
        img: [product2a, product2b, product2a, product2b],
        price: 187,
        discount: 17,
        category: 'jean',
        title: 'Blue Jeans',
    },
    {
        id: 89,
        img: [product2a, product2b, product2a, product2b],
        price: 195,
        discount: 17,
        category: 'jean',
        title: 'Boy Jeans',
    },
    {
        id: 90,
        img: [product2a, product2b, product2a, product2b],
        price: 225,
        discount: 17,
        category: 'jean',
        title: 'Gray Jeans',
    },
    {
        id: 91,
        img: [product2a, product2b, product2a, product2b],
        price: 246,
        discount: 17,
        category: 'jean',
        title: 'Green Jeans',
    },
    {
        id: 92,
        img: [product2a, product2b, product2a, product2b],
        price: 179,
        discount: 17,
        category: 'jean',
        title: 'Red Jeans',
    },
    {
        id: 93,
        img: [product2a, product2b, product2a, product2b],
        price: 184,
        discount: 17,
        category: 'jean',
        title: 'Yellow Jeans',
    },
    {
        id: 94,
        img: [product2a, product2b, product2a, product2b],
        price: 179,
        discount: 17,
        category: 'jean',
        title: 'Pink Jeans',
    },
    {
        id: 95,
        img: [product2a, product2b, product2a, product2b],
        price: 169,
        discount: 17,
        category: 'jean',
        title: 'Orange Jeans',
    },
    {
        id: 96,
        img: [product2a, product2b, product2a, product2b],
        price: 216,
        discount: 17,
        category: 'jean',
        title: 'Purple Jeans',
    },
    {
        id: 97,
        img: [product2a, product2b, product2a, product2b],
        price: 227,
        discount: 0,
        category: 'san.d',
        title: 'Pique Polo San.D',
    },
    {
        id: 98,
        img: [product2a, product2b, product2a, product2b],
        price: 171,
        discount: 0,
        category: 'san.d',
        title: 'Mesh Polo San.D',
    },
    {
        id: 99,
        img: [product2a, product2b, product2a, product2b],
        price: 207,
        discount: 0,
        category: 'san.d',
        title: 'Color Block Polo San.D',
    },
    {
        id: 100,
        img: [product2a, product2b, product2a, product2b],
        price: 231,
        discount: 0,
        category: 'san.d',
        title: 'Button-Down Polo San.D',
    },
];

const jeans = [,];

export const productsPerPage = 12;
